<?php

namespace App\Models;


use App\Observers\FangObserver;
use Illuminate\Database\Eloquent\Model;
use App\Models\Traits\Bth;

class Fang extends Model
{
    private static $host='http://www.zf.com/';
    use Bth;
    protected $guarded=[];
        //调用观察者-》调用消息队列-》向es中添加数据供分词搜索
//    protected static function boot()
//    {
//        parent::boot(); // TODO: Change the autogenerated stub
//        self::observe(FangObserver::class);
//    }

    public function fangowner()
    {
        return $this->belongsTo(FangOwner::class,'fang_owner');
    }
    //fang表中配套设施选项字段匹配fangattr表中对应的数据
    public function getAttrIdByName($id)
    {
        if(!is_array($id)){
            //一对一取
            return Fangattr::where('id',$id)->value('name');
        }
        $name=Fangattr::whereIn('id',$id)->pluck('name')->toArray();
        return implode(',',$name);
    }
    //获取器
    public function getFangPicAttribute()
    {
        //将图片地址拼接的字符串转换为数组
        $arr=explode('#',$this->attributes['fang_pic']);
        //去出第一个元素
        array_shift($arr);
        return array_map(function ($item){
            return self::$host . '/' . ltrim($item,'/');
        },$arr);
    }
}
