<?php

namespace App\Models;


use App\Observers\FangObserver;
use Illuminate\Database\Eloquent\Model;

class Fang extends Model
{
    protected $guarded=[];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::observe(FangObserver::class);
    }


}
