<?php

namespace App\Models;

use App\Observers\FangOwenerObserver;
use App\Observers\FangOwnerObserver;
use Illuminate\Database\Eloquent\Model;

class FangOwner extends Model
{
    //
    protected $guarded=[];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::observe(FangOwnerObserver::class);
    }

}
